trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'webApp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet
- task: NuGetToolInstaller@1

# Restore packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build and publish using MSBuild
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'Azure connection'
    appName: 'tpcsapp'
    resourceGroupName: 'DevopsRG1'
    package: '$(build.artifactStagingDirectory)/**/*.zip'

